import Head from "next/head";
import Colors from "../components/Colors";
import GlobalNavbar from "../components/GlobalNavbar";
import Hero from "../components/Hero";
import HeroInfo from "../components/HeroInfo";
import LocalNavbar from "../components/LocalNavbar";
import M1 from "../components/M1";

export default function Home() {
  return (
    <div>
      <Head>
        <title>iMac 24-inch - Apple</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <GlobalNavbar />
      <LocalNavbar />
      <Hero />
      <HeroInfo />
      <Colors />
      <M1 />
    </div>
  );
}
